name: "LFTP"
description: 'Sync directories via ftp'
inputs:
  username:  # id of input
    description: 'username for ftp'
    required: true
  password:  # id of input
    description: 'password'
    required: true
  host:  # id of input
    description: 'server url'
    required: true

runs:
  using: 'docker'
  image: 'docker://rickvm/lftp:latest'
  args:
    - ${{ inputs.who-to-greet }}

branding:
  icon: 'upload-cloud'  
  color: 'green'
